system:
  save_step: 5

model:
  model_name: 'efficientnet_b0'
  pretrained: True
  num_classes: 10038
  drop_rate: 0.2
  drop_path: 0.2

dataset:
  pre_transform: False
  batch_size: 768
  scale: (0.08, 1.0)
  reprob: 0.2
  remode: 'pixel'
  aa: 'rand-m9-mstd0.5'
  train_interpolation: 'random'
  workers: 20

optimizer:
  opt: 'rmsproptf'
  lr: .048
  opt_eps: .001
  momentum: 0.9
  weight_decay: 1e-5

scheduler:
  sched: 'step'
  epochs: 50
  decay_epochs: 2.4
  decay_rate: .97
  warmup_lr: 1e-6
  warmup_epochs: 3
