version: "3.7"
  
services:
  fastapi:
    image: fastapi
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    build:
      context: . # Dockerfile locate
      dockerfile: Dockerfile
    volumes:
      - ./app:/code/app

        #command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
